---
version: "2.1"

x-env: &env
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  restart: unless-stopped

x-env: &image
  image: lscr.io/linuxserver/sonarr:develop

services:
  sonarr:
    <<: *image
    <<: *env
    container_name: sonarr
    volumes:
      - ${SONARR_LOC_1080P}:/config
      - ${MEDIA_LIB_1}:/data
      - ${MEDIA_LIB_2}:/data-dsnine
    ports:
      - ${SONARR_1080P}:8989
  sonarr-4k:
    <<: *image
    <<: *env
    container_name: sonarr-4k
    volumes:
      - ${SONARR_LOC_4K}:/config
      - ${MEDIA_LIB_2}:/data-dsnine
    ports:
      - ${SONARR_4K}:8989
  sonarr-anime:
    <<: *image
    <<: *env
    container_name: sonarr-anime
    volumes:
      - ${SONARR_LOC_ANIME}:/config
      - ${MEDIA_LIB_1}:/data
      - ${MEDIA_LIB_2}:/data-dsnine
    ports:
      - ${SONARR_ANIME}:8989